project:
  type: website
  output-dir: docs

website:
  title: "humzaakhan.github.io"
  navbar:
    left:
      - href: about.qmd
        text: Humza Khan
      - href: workingpapers.qmd
        text: Working Papers
      - href: Humza Khan CV.pdf
        text: CV
      - href: researchinterests.qmd
        text: Research Interests
    
      - href: assignment2.qmd
        text: Assignment 2
      

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual